export interface GithubApiCommit {
  author: {
    name: string
    email: string
    date: string
  }
  committer: {
    name: string
    email: string
    date: string
  }
  message: string
  tree: {
    sha: string
    url: string
  }
  url: string
  comment_count: number
  verification?: {
    verified: boolean
    reason: string
    signature: string
    payload: string
  }
}

export interface GithubApiPr {
  url: string
  id: number
  number: number
  title: string
  state: string
  user: {
    login: string
    id: number
    node_id: string
    avatar_url: string
    gravatar_id: string
    url: string
    type: string
    site_admin: boolean
  }
  body: string
  created_at: string
  updated_at: string
  closed_at: null
  merged_at: null
  merge_commit_sha: null
  assignee: {
    login: string
    id: number
    node_id: string
    avatar_url: string
    gravatar_id: string
    url: string
    html_url: string
    followers_url: string
    following_url: string
    gists_url: string
    starred_url: string
    subscriptions_url: string
    organizations_url: string
    repos_url: string
    events_url: string
    received_events_url: string
    type: string
    site_admin: boolean
  }
  assignees: [
    {
      login: string
      id: number
      node_id: string
      avatar_url: string
      gravatar_id: string
      url: string
      html_url: string
      followers_url: string
      following_url: string
      gists_url: string
      starred_url: string
      subscriptions_url: string
      organizations_url: string
      repos_url: string
      events_url: string
      received_events_url: string
      type: string
      site_admin: boolean
    }
  ]
  requested_reviewers: []
  requested_teams: []
  labels: {
    id: number
    node_id: string
    url: string
    name: string
    color: string
    default: boolean
  }[]
  milestone: null
  commits_url: string
  review_comments_url: string
  review_comment_url: string
  comments_url: string
  statuses_url: string
  head: {
    label: string
    ref: string
    sha: string
    user: {
      login: string
      id: number
      node_id: string
      avatar_url: string
      gravatar_id: string
      url: string
      html_url: string
      followers_url: string
      following_url: string
      gists_url: string
      starred_url: string
      subscriptions_url: string
      organizations_url: string
      repos_url: string
      events_url: string
      received_events_url: string
      type: string
      site_admin: boolean
    }
    repo: {
      id: number
      node_id: string
      name: string
      full_name: string
      private: boolean
      owner: {
        login: string
        id: number
        node_id: string
        avatar_url: string
        gravatar_id: string
        url: string
        html_url: string
        followers_url: string
        following_url: string
        gists_url: string
        starred_url: string
        subscriptions_url: string
        organizations_url: string
        repos_url: string
        events_url: string
        received_events_url: string
        type: string
        site_admin: boolean
      }
      html_url: string
      description: string
      fork: true
      url: string
      forks_url: string
      keys_url: string
      collaborators_url: string
      teams_url: string
      hooks_url: string
      issue_events_url: string
      events_url: string
      assignees_url: string
      branches_url: string
      tags_url: string
      blobs_url: string
      git_tags_url: string
      git_refs_url: string
      trees_url: string
      statuses_url: string
      languages_url: string
      stargazers_url: string
      contributors_url: string
      subscribers_url: string
      subscription_url: string
      commits_url: string
      git_commits_url: string
      comments_url: string
      issue_comment_url: string
      contents_url: string
      compare_url: string
      merges_url: string
      archive_url: string
      downloads_url: string
      issues_url: string
      pulls_url: string
      milestones_url: string
      notifications_url: string
      labels_url: string
      releases_url: string
      deployments_url: string
      created_at: string
      updated_at: string
      pushed_at: string
      git_url: string
      ssh_url: string
      clone_url: string
      svn_url: string
      homepage: string
      size: 747223
      stargazers_count: 0
      watchers_count: 0
      language: string
      has_issues: boolean
      has_projects: true
      has_downloads: true
      has_wiki: true
      has_pages: boolean
      forks_count: 0
      mirror_url: null
      archived: boolean
      disabled: boolean
      open_issues_count: 0
      license: {
        key: string
        name: string
        spdx_id: string
        url: null
        node_id: string
      }
      forks: number
      open_issues: number
      watchers: number
      default_branch: string
    }
  }
  base: {
    label: string
    ref: string
    sha: string
    user: {
      login: string
      id: 6764390
      node_id: string
      avatar_url: string
      gravatar_id: string
      url: string
      html_url: string
      followers_url: string
      following_url: string
      gists_url: string
      starred_url: string
      subscriptions_url: string
      organizations_url: string
      repos_url: string
      events_url: string
      received_events_url: string
      type: string
      site_admin: boolean
    }
    repo: {
      id: 7833168
      node_id: string
      name: string
      full_name: string
      private: boolean
      owner: {
        login: string
        id: 6764390
        node_id: string
        avatar_url: string
        gravatar_id: string
        url: string
        html_url: string
        followers_url: string
        following_url: string
        gists_url: string
        starred_url: string
        subscriptions_url: string
        organizations_url: string
        repos_url: string
        events_url: string
        received_events_url: string
        type: string
        site_admin: boolean
      }
      html_url: string
      description: string
      fork: boolean
      url: string
      forks_url: string
      keys_url: string
      collaborators_url: string
      teams_url: string
      hooks_url: string
      issue_events_url: string
      events_url: string
      assignees_url: string
      branches_url: string
      tags_url: string
      blobs_url: string
      git_tags_url: string
      git_refs_url: string
      trees_url: string
      statuses_url: string
      languages_url: string
      stargazers_url: string
      contributors_url: string
      subscribers_url: string
      subscription_url: string
      commits_url: string
      git_commits_url: string
      comments_url: string
      issue_comment_url: string
      contents_url: string
      compare_url: string
      merges_url: string
      archive_url: string
      downloads_url: string
      issues_url: string
      pulls_url: string
      milestones_url: string
      notifications_url: string
      labels_url: string
      releases_url: string
      deployments_url: string
      created_at: string
      updated_at: string
      pushed_at: string
      git_url: string
      ssh_url: string
      clone_url: string
      svn_url: string
      homepage: string
      size: 774115
      stargazers_count: 11615
      watchers_count: 11615
      language: string
      has_issues: true
      has_projects: true
      has_downloads: true
      has_wiki: true
      has_pages: boolean
      forks_count: 4544
      mirror_url: null
      archived: boolean
      disabled: boolean
      open_issues_count: 4344
      license: {
        key: string
        name: string
        spdx_id: string
        url: null
        node_id: string
      }
      forks: 4544
      open_issues: 4344
      watchers: 11615
      default_branch: string
    }
  }
  _links: {
    self: {
      href: string
    }
    html: {
      href: string
    }
    issue: {
      href: string
    }
    comments: {
      href: string
    }
    review_comments: {
      href: string
    }
    review_comment: {
      href: string
    }
    commits: {
      href: string
    }
    statuses: {
      href: string
    }
  }
  author_association: string
  draft: true
  mergeable_state: string
  merged_by: any
  comments: number
  review_comments: number
  maintainer_can_modify: true
  commits: number
  additions: number
  deletions: number
  changed_files: number
}
