import { getConfigVar } from '@spalger/micro-plus'
import { GithubApi } from './github_api'
import { createRootLog } from './log'

const log = createRootLog(null)

describe('getPrsAndFiles()', () => {
  it('gets expected result', async () => {
    const api = new GithubApi(log, getConfigVar('GITHUB_SECRET'))
    await expect(
      api.getPrsAndFiles('3c8ae0aaeb3c5e6c34c16617efa12d3bc8846439', 'closed'),
    ).resolves.toMatchInlineSnapshot(`
            Array [
              Object {
                "files": Array [
                  "Jenkinsfile",
                  "src/dev/failed_tests/cli.js",
                  "test/scripts/jenkins_ci_group.sh",
                  "test/scripts/jenkins_firefox_smoke.sh",
                  "test/scripts/jenkins_unit.sh",
                  "test/scripts/jenkins_visual_regression.sh",
                  "test/scripts/jenkins_xpack.sh",
                  "test/scripts/jenkins_xpack_ci_group.sh",
                  "test/scripts/jenkins_xpack_firefox_smoke.sh",
                  "test/scripts/jenkins_xpack_visual_regression.sh",
                ],
                "id": 45551,
                "updatedSinceCommit": false,
              },
            ]
          `)

    await expect(
      api.getPrsAndFiles('7bfe7566dddb4ec020937537899ddd5cdb595c21', 'closed'),
    ).resolves.toMatchInlineSnapshot(`
            Array [
              Object {
                "files": Array [
                  "x-pack/legacy/plugins/ml/common/constants/app.ts",
                  "x-pack/legacy/plugins/ml/common/constants/feature_flags.ts",
                  "x-pack/legacy/plugins/ml/common/constants/new_job.ts",
                  "x-pack/legacy/plugins/ml/common/types/kibana.ts",
                  "x-pack/legacy/plugins/ml/common/util/job_utils.js",
                  "x-pack/legacy/plugins/ml/index.ts",
                  "x-pack/legacy/plugins/ml/kibana.json",
                  "x-pack/legacy/plugins/ml/public/application/access_denied/index.tsx",
                  "x-pack/legacy/plugins/ml/public/application/access_denied/page.tsx",
                  "x-pack/legacy/plugins/ml/public/application/app.js",
                  "x-pack/legacy/plugins/ml/public/application/app.tsx",
                  "x-pack/legacy/plugins/ml/public/application/components/annotations/annotations_table/annotations_table.js",
                  "x-pack/legacy/plugins/ml/public/application/components/anomalies_table/links_menu.js",
                  "x-pack/legacy/plugins/ml/public/application/components/data_recognizer/data_recognizer.d.ts",
                  "x-pack/legacy/plugins/ml/public/application/components/data_recognizer/recognized_result.js",
                  "x-pack/legacy/plugins/ml/public/application/components/navigation_menu/main_tabs.tsx",
                  "x-pack/legacy/plugins/ml/public/application/components/navigation_menu/tabs.tsx",
                  "x-pack/legacy/plugins/ml/public/application/contexts/kibana/__mocks__/saved_search.ts",
                  "x-pack/legacy/plugins/ml/public/application/contexts/kibana/kibana_context.ts",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_exploration/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_exploration/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_exploration/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_management/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_management/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/data_frame_analytics/pages/analytics_management/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/datavisualizer_selector.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/components/import_view/import_view.js",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/components/results_links/results_links.js",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/file_datavisualizer.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/file_datavisualizer_directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/file_based/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/components/actions_panel/actions_panel.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/page.tsx",
                  "x-pack/legacy/plugins/ml/public/application/datavisualizer/index_based/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/explorer/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/explorer/explorer.js",
                  "x-pack/legacy/plugins/ml/public/application/explorer/explorer_directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/explorer/explorer_route.ts",
                  "x-pack/legacy/plugins/ml/public/application/explorer/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/index.scss",
                  "x-pack/legacy/plugins/ml/public/application/jobs/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/components/job_actions/results.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/components/job_details/extract_job_details.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/components/job_details/forecasts_table/forecasts_table.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/components/jobs_list_view/jobs_list_view.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/directive.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/jobs_list/jobs.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/advanced_job_creator.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/configs/job.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/job_creator.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/job_creator_factory.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/multi_metric_job_creator.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/population_job_creator.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/single_metric_job_creator.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/type_guards.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/job_creator/util/general.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/common/results_loader/results_loader.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/datafeed_step/components/query_delay/query_delay_input.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/job_details_step/components/advanced_section/advanced_section.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/pick_fields_step/components/multi_metric_view/chart_grid.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/pick_fields_step/components/population_view/chart_grid.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/pick_fields_step/components/split_cards/split_cards.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/pick_fields_step/components/split_field/description.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/pick_fields_step/pick_fields.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/summary_step/components/datafeed_details/datafeed_details.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/summary_step/components/detector_chart/detector_chart.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/summary_step/summary.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/time_range_step/time_range.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/components/validation_step/validation.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/index_or_search/__test__/directive.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/index_or_search/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/index_or_search/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/index_or_search/preconfigured_job_redirect.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/index_or_search/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/job_type/__test__/directive.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/job_type/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/job_type/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/job_type/page.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/job_type/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/page.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/wizard.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/wizard_horizontal_steps.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/pages/new_job/wizard_steps.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/__test__/directive.js",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/page.tsx",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/resolvers.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/recognize/route.ts",
                  "x-pack/legacy/plugins/ml/public/application/jobs/new_job/utils/new_job_utils.ts",
                  "x-pack/legacy/plugins/ml/public/application/overview/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/overview/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/overview/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/resolvers.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/router.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/access_denied.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/data_frame_analytics/analytics_job_exploration.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/data_frame_analytics/analytics_jobs_list.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/data_frame_analytics/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/datavisualizer/datavisualizer.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/datavisualizer/file_based.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/datavisualizer/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/datavisualizer/index_based.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/explorer.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/jobs_list.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/index_or_search.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/job_type.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/new_job.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/recognize.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/new_job/wizard.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/overview.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/calendar_list.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/calendar_new_edit.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/filter_list.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/filter_list_new_edit.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/settings/settings.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/routes/timeseriesexplorer.tsx",
                  "x-pack/legacy/plugins/ml/public/application/routing/use_resolver.ts",
                  "x-pack/legacy/plugins/ml/public/application/services/job_service.d.ts",
                  "x-pack/legacy/plugins/ml/public/application/services/job_service.js",
                  "x-pack/legacy/plugins/ml/public/application/services/new_job_capabilities_service.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/breadcrumbs.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/calendar_form/__snapshots__/calendar_form.test.js.snap",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/calendar_form/calendar_form.js",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/new_calendar.d.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/edit/new_calendar.js",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/list/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/list/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/list/table/__snapshots__/table.test.js.snap",
                  "x-pack/legacy/plugins/ml/public/application/settings/calendars/list/table/table.js",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/edit/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/edit/edit_filter_list.d.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/edit/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/list/directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/list/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/filter_lists/list/table.js",
                  "x-pack/legacy/plugins/ml/public/application/settings/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/settings/settings.tsx",
                  "x-pack/legacy/plugins/ml/public/application/settings/settings_directive.tsx",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/breadcrumbs.js",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/index.js",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/index.ts",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/timeseriesexplorer.d.ts",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/timeseriesexplorer.js",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/timeseriesexplorer_directive.js",
                  "x-pack/legacy/plugins/ml/public/application/timeseriesexplorer/timeseriesexplorer_route.js",
                  "x-pack/legacy/plugins/ml/public/application/util/chart_utils.js",
                  "x-pack/legacy/plugins/ml/public/application/util/chart_utils.test.js",
                  "x-pack/legacy/plugins/ml/public/application/util/index_utils.ts",
                  "x-pack/legacy/plugins/ml/public/index.scss",
                  "x-pack/legacy/plugins/ml/public/index.ts",
                  "x-pack/legacy/plugins/ml/public/legacy.ts",
                  "x-pack/legacy/plugins/ml/public/plugin.ts",
                  "x-pack/legacy/plugins/ml/server/models/job_service/new_job/line_chart.ts",
                  "x-pack/plugins/translations/translations/ja-JP.json",
                  "x-pack/plugins/translations/translations/zh-CN.json",
                ],
                "id": 52770,
                "updatedSinceCommit": false,
              },
            ]
          `)
  }, 60000)
})
