import { GithubUser } from './user'

export interface GithubRepo {
  id: number
  node_id: unknown
  name: unknown
  full_name: unknown
  private: unknown
  owner: GithubUser
  html_url: unknown
  description: unknown
  fork: unknown
  url: unknown
  forks_url: unknown
  keys_url: unknown
  collaborators_url: unknown
  teams_url: unknown
  hooks_url: unknown
  issue_events_url: unknown
  events_url: unknown
  assignees_url: unknown
  branches_url: unknown
  tags_url: unknown
  blobs_url: unknown
  git_tags_url: unknown
  git_refs_url: unknown
  trees_url: unknown
  statuses_url: unknown
  languages_url: unknown
  stargazers_url: unknown
  contributors_url: unknown
  subscribers_url: unknown
  subscription_url: unknown
  commits_url: unknown
  git_commits_url: unknown
  comments_url: unknown
  issue_comment_url: unknown
  contents_url: unknown
  compare_url: unknown
  merges_url: unknown
  archive_url: unknown
  downloads_url: unknown
  issues_url: unknown
  pulls_url: unknown
  milestones_url: unknown
  notifications_url: unknown
  labels_url: unknown
  releases_url: unknown
  deployments_url: unknown
  created_at: unknown
  updated_at: unknown
  pushed_at: unknown
  git_url: unknown
  ssh_url: unknown
  clone_url: unknown
  svn_url: unknown
  homepage: unknown
  size: unknown
  stargazers_count: unknown
  watchers_count: unknown
  language: unknown
  has_issues: unknown
  has_projects: unknown
  has_downloads: unknown
  has_wiki: unknown
  has_pages: unknown
  forks_count: unknown
  mirror_url: unknown
  archived: unknown
  disabled: unknown
  open_issues_count: unknown
  license: unknown
  forks: unknown
  open_issues: unknown
  watchers: unknown
  default_branch: unknown
  stargazers: unknown
  master_branch: unknown
  organization: unknown
}
